import Head from 'next/head';
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillInstagram, AiFillGithub, AiFillAudio, AiFillChrome } from 'react-icons/ai';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { useState } from 'react';
import deved from '../public/Profil.jpg';
import code from '../public/code.png';
import design from '../public/design.png';
import consulting from '../public/consulting.png';
import Image from 'next/image';
import web1 from '../public/Perpustakaan.png';
import web2 from '../public/TTS.jpeg';
import web3 from '../public/Letter.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ''}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">BintangFauzan</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=" cursor-pointer text-2xl" />
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" href="https://drive.google.com/file/d/1ejV5CajOon7B3I-VWstn0F7P1bIIcvY2/view?usp=sharing">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">Bintang Fauzan Dyan</h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">Developer.</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Seorang lulusan dengan gelar Sarjana dalam Ilmu Komputer yang antusias dan siap memulai karir di bidang teknologi informasi. Memiliki pemahaman dasar tentang pengembangan, pemrograman, dan pengembangan perangkat lunak, serta
              analisis sistem. Mampu bekerja dalam tim dan memiliki kemampuan belajar yang cepat. Berkomitmen untuk mengembangkan keterampilan dan berkontribusi pada proyek-proyek yang menantang.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.instagram.com/bintang_fauzan14?igsh=NGpxb3JieW50ODFt">
                <AiFillInstagram />
              </a>
              <a href="https://www.linkedin.com/in/bintang-fauzan-62a760203" target="_blank" rel="noopener noreferrer">
                <AiFillLinkedin />
              </a>
              {/* <AiFillYoutube /> */}
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        {/* <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">I offer from a wide range of services, including brand design, programming and teaching.</p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">Beautiful Designs</h3>
              <p className="py-2">Creating elegant designs suited for your needs following core design theory.</p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Code your dream project</h3>
              <p className="py-2">Do you have an idea for your next great website? Let's make it a reality.</p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">Are you interested in feedback for your current project? I can give you tips and tricks to level it up.</p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
          </div>
        </section> */}
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Project</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Sebagai lulusan Teknik Informatika, saya sangat antusias untuk memulai perjalanan profesional saya di dunia teknologi. Meskipun saya belum memiliki pengalaman kerja formal, saya telah terlibat dalam berbagai proyek akademis
              dan pribadi yang memungkinkan saya untuk mengembangkan keterampilan dalam pengembangan perangkat lunak, pemrograman, dan analisis sistem. Saya berkomitmen untuk terus belajar dan beradaptasi dengan teknologi terbaru, serta
              siap untuk berkontribusi dalam proyek-proyek yang menantang. Saya percaya bahwa dengan semangat dan dedikasi, saya dapat memberikan nilai tambah bagi tim dan perusahaan yang saya bergabung.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <div className="max-w-sm rounded overflow-hidden shadow-lg bg-white dark:bg-gray-800">
                <a href="https://github.com/BintangFauzan/UAS_PEMWEB_02">
                  <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" src={web1} />
                </a>
                <div className="p-4">
                  <h2 className="text-lg font-bold text-gray-900 dark:text-white">Perpustakaan Digital</h2>
                  <p className="text-gray-700 dark:text-gray-300">Membuat Sistem Perpustakaan Dengan Vue dan PHP sebagai FrameWorknya</p>
                  <a href="https://github.com/BintangFauzan/UAS_PEMWEB_02" className="mt-4 inline-block bg-blue-500 dark:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    <AiFillGithub />
                  </a>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="max-w-sm rounded overflow-hidden shadow-lg bg-white dark:bg-gray-800">
                <a href="https://github.com/BintangFauzan/UAS_PEMWEB_02">
                  <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" src={web2} />
                </a>
                <div className="p-4">
                  <h2 className="text-lg font-bold text-gray-900 dark:text-white">Text To Speech Bahasa Minang</h2>
                  <p className="text-gray-700 dark:text-gray-300">Membuat Sistem Text To Speech Bahasa Minang Dengan Menggunakan Metode VITS</p>
                  <a href="https://colab.research.google.com/drive/1w1lDT_ATJM7PbIguZyUb-k1RBzJa8X3u?usp=sharing" className="mt-4 inline-block bg-blue-500 dark:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    <AiFillAudio />
                  </a>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <div className="max-w-sm rounded overflow-hidden shadow-lg bg-white dark:bg-gray-800">
                <a href="https://github.com/BintangFauzan/UAS_PEMWEB_02">
                  <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" src={web3} />
                </a>
                <div className="p-4">
                  <h2 className="text-lg font-bold text-gray-900 dark:text-white">Making A Game</h2>
                  <p className="text-gray-700 dark:text-gray-300">Membuat Game RPG 2D Dengan Menggunakan RPG Maker MV</p>
                  <a href="https://bintangfauzan.github.io/The-Letter/" className="mt-4 inline-block bg-blue-500 dark:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    <AiFillChrome />
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
